version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/config/kibana.yml
        read_only: true
    ports:
      - "5602:5602"
    networks:
      - elk
    depends_on:
      - elasticsearch

  httpd:
    build:
      context: httpd/
    volumes:
      - type: bind
        source: ./httpd/config/filebeat.yml
        target: /etc/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./httpd/config/metricbeat.yml
        target: /etc/metricbeat/metricbeat.yml
        read_only: true
      - type: bind
        source: ./httpd/config/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
        read_only: true
      - type: bind
        source: /var/log/auth.log
        target: /var/log/auth.log
        read_only: true
      # - type: bind
      #   source: /var/log/syslog
      #   target: /var/log/syslog
      #   read_only: true
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/config/kibana.yml
        read_only: true
    ports:
      - "80:80"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
